import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/lib/providers/query-provider";
import Header from "@/components/layouts/header-main";
import Footer from "@/components/layouts/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` antialiased`}>
        <QueryProvider>
          <div className="min-h-screen w-full bg-[#020617] fixed top-0 left-0 bottom-0">
            {/* Dark Radial Glow Background */}
            <div
              className=" absolute inset-0 z-0"
              style={{
                backgroundImage: `radial-gradient(circle 500px at 50% 200px, #3e3e3e, transparent)`,
              }}
            />
            {/* Your Content/Components */}
          </div>
          <main className=" absolute top-0 w-full left-0">
            <Header />
            {children}
            <Footer />
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
